author: Matthew Wright
title: mwrightdev.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mwright.com"

# Footer
#email: matthew@mwrightdev.com
github_username:    DevWright
linkedin_username:  mwrightdev
# twitter_username:   mwrightdev
description: >
  This site is under constant development. It began with the jekyll minima
  layout, and will be improved as I learn CSS and HTML. 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
